### ISSUE TITLE
spree_sample no images Docker

### ISSUE THREAD

**Issue by abbasahmad** [spree/spree_starter#1002]
When i load the samples with 
docker-compose run web rake spree_sample:load

I have no images loaded in the poducts, is this normal ?

![image](https://user-images.githubusercontent.com/8807863/160854728-ce535cbb-a020-4595-b1b0-bdb5e3da5158.png)

**Comment by abbasahmad** [comment]
Nothing on this ? No one has this issue ? No one can replicate ?  [https://github.com/spree/spree/issues/11671#issue-1186960249](https://github.com/spree/spree/issues/11671#issue-1186960249)

**Comment by rafalcymerys** [comment]
Let's use https://github.com/spree/spree/issues/10865 to keep track of this issue
