### ISSUE TITLE
Command "start-hybrid" spins up container with web app

### ISSUE THREAD

**Issue by nciemniak** [spree/spree_starter#1021]
Starting the app in hybrid mode should spin up docker containers for redis and postgres, while leaving the web app itself to be run locally on the user's machine. `start-hybrid` is currently spinning up a container for the web app (and later bringing it down again), despite the fact that all processes for the web app are meant to be run locally. Spinning up a container and installing dependencies ends up slowing down the process of getting the app up and running.

Requirements:
- remove process for creating a docker container for the web app from `start-hybrid` script
- any commands run inside the docker container pertaining to the web app (e.g. migrations) should be moved to the instructions in the section "After loading all docker dependencies..."

**Comment by rafalcymerys** [comment]
I'm reviewing that and another thing I would take a look at is showing a warning when running spree dockerized on mac. It's very slow due to how docker's filesystem sync works on Mac - it would be great to at least display a warning there.
