### ISSUE TITLE
We're sorry, but something went wrong. If you are the application owner check the logs for more information.

### ISSUE THREAD

**Issue by ploitivel** [spree/spree_starter#1053]
I get the following error at http://0.0.0.0:4000/admin/login

We're sorry, but something went wrong.
If you are the application owner check the logs for more information.

When reviewing the logs of the container already compiled in production, I get the following error
$docker logs container

I, [2023-01-21T19:18:44.376702 #51] INFO -- : [ae9df578-5457-4485-a3c2-88ad34b31cb8] Completed 500 Internal Server Error in 439ms (ActiveRecord: 59.6ms | Allocations: 26850)
F, [2023-01-21T19:18:44.380758 #51] FATAL -- : [ae9df578-5457-4485-a3c2-88ad34b31cb8]
[ae9df578-5457-4485-a3c2-88ad34b31cb8] ActionView::Template::Error (The asset "spree/backend/all.css" is not present in the asset pipeline.
):
[ae9df578-5457-4485-a3c2-88ad34b31cb8] 13: <% end %>
[ae9df578-5457-4485-a3c2-88ad34b31cb8] 14: </title>
[ae9df578-5457-4485-a3c2-88ad34b31cb8] 15:
[ae9df578-5457-4485-a3c2-88ad34b31cb8] 16: <%= stylesheet_link_tag 'spree/backend/all', media: :all %>
[ae9df578-5457-4485-a3c2-88ad34b31cb8] 17:
[ae9df578-5457-4485-a3c2-88ad34b31cb8] 18: <script>
[ae9df578-5457-4485-a3c2-88ad34b31cb8] 19: <%== "var AUTH_TOKEN = #{form_authenticity_token.inspect};" %>
[ae9df578-5457-4485-a3c2-88ad34b31cb8]
[ae9df578-5457-4485-a3c2-88ad34b31cb8] lib/cloud_flare_middleware.rb:18:in `call'
I, [2023-01-21T19:18:44.393543 #51] INFO -- : source=rack-timeout id=ae9df578-5457-4485-a3c2-88ad34b31cb8 timeout=15000ms service=466ms state=completed

**Comment by rafalcymerys** [comment]
Hi @ploitivel - this seems like an issue caused by assets not being precompiled. Did you get any issues from the rails assets:precompile step when building or running the image?
