### ISSUE TITLE
No routes working except admin

### ISSUE THREAD

**Issue by nicknetender** [spree/spree_starter#1072]
I am using a clean, fresh installation using Docker with sample seed data fed into the database.

I am able to log in to the admin, however no other URL works including:

- / (shows the default Rails landing page for empty apps)
- /login
- /signup
- /pages/about-us
- /products/3-4-sleeve-t-shirt (or any other product)
- ... and so on

Server logs
```
ActionController::RoutingError (No route matches [GET] "/pages/about-us"):
```

config/routes.rb
```
Rails.application.routes.draw do
  # Spree routes
  mount Spree::Core::Engine, at: '/'

  # sidekiq web UI
  require 'sidekiq/web'
  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    username == Rails.application.secrets.sidekiq_username &&
      password == Rails.application.secrets.sidekiq_password
  end

  mount Sidekiq::Web, at: '/sidekiq'
end

```

Am I doing something wrong?...

**Comment by damianlegawiec** [comment]
Hi @nicknetender 

The previous version didn't include the storefront by default. We rebuilt the starter to be an all-in-one package now
