### ISSUE TITLE
Issue in connection with database using Docker in development env. 

### ISSUE THREAD

**Issue by Gursehaj** [spree/spree_starter#1147]
I run the spree app using `docker run <image_name>:<tag>`. And spin up the database using `docker compose up`. This results in spree throwing the following error:

> $ docker run skipqbackend:1.0.0
bin/rails aborted!
ActiveRecord::ConnectionNotEstablished: connection to server at "::1", port 5432 failed: Connection refused (ActiveRecord::ConnectionNotEstablished)  
        Is the server running on that host and accepting TCP/IP connections?
connection to server at "127.0.0.1", port 5432 failed: Connection refused
        Is the server running on that host and accepting TCP/IP connections?
Caused by:
PG::ConnectionBad: connection to server at "::1", port 5432 failed: Connection refused (PG::ConnectionBad)
        Is the server running on that host and accepting TCP/IP connections?
connection to server at "127.0.0.1", port 5432 failed: Connection refused
        Is the server running on that host and accepting TCP/IP connections?
Tasks: TOP => db:prepare
(See full trace by running task with --trace)
(base)  

I changed the rails environment from production to development within the docker file.

**Comment by damianlegawiec** [comment]
This is now resolved as we switched to sqlite for docker image and it doesn't;t require additional services :)
