### ISSUE TITLE
Changing `Gemfile` takes `docker compose build` ~5 minutes to complete

### ISSUE THREAD

**Issue by vfonic** [spree/spree_starter#953]
I noticed that for any change that I make in `Gemfile`, `docker compose build` takes almost 5 minutes to finish.

Isn't there any way to make this faster?

These issues, no matter how small they sound, are a huge pain point to me. I'm starting a new Spree project and I would like to develop rapidly, in a way that Rails allows me to do.

Running `bundle install` locally takes about 0.5 seconds.
Using this project's recommended Docker setup, `bundle install && docker compose build` takes about 5 minutes.

I'll be adding many Spree extensions as gems. I don't want to wait 5 minutes every time I add a new gem.

How can we avoid this?

**Comment by damianlegawiec** [comment]
The initial build will take a longer time. Additional re-builds will use docker cache and should be much faster.

**Comment by vfonic** [comment]
Is there any reason why a full build is needed? It seems to me like I could just do `docker compose run web bundle install`. I've tried this and it seems to work. It takes a couple of seconds to run.

I'm not very familiar with Docker, but this seems like a better approach to me.

What do you think?

**Comment by damianlegawiec** [comment]
> Is there any reason why a full build is needed? It seems to me like I could just do `docker compose run web bundle install`. I've tried this and it seems to work. It takes a couple of seconds to run.
> 
> 
> 
> I'm not very familiar with Docker, but this seems like a better approach to me.
> 
> 
> 
> What do you think?

Hmm full rebuild shouldn't be required, will take a look next week

**Comment by vfonic** [comment]
It could be that the instructions in README are slightly misleading:

>### Adding new gems
>
>Update `Gemfile` and run
>
>```bash
>bundle install
>docker-compose build
>```
>
>You will need to restart the server if running:
>
>```bash
>docker-compose restart
>```
>
>### Updating gems
>
>```bash
>bundle update spree
>docker-compose build
>```

These `bundle` commands should probably be run inside docker.

**Comment by damianlegawiec** [comment]
Closing this as we've moved away from all things being inside docker container now
