### ISSUE TITLE
install failed

### ISSUE THREAD

**Issue by pangoo-reuse** [spree/spree_starter#956]
[help]
my env:
ruby 2.7.3 ,rails 6.1.4

`Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /bundle/ruby/2.7.0/gems/racc-1.5.2/ext/racc/cparse
/usr/local/bin/ruby -I /usr/local/lib/ruby/2.7.0 -r
./siteconf20210816-6-1h6cbus.rb extconf.rb
extconf failedCannot allocate memory - /usr/local/bin/ruby

Gem files will remain installed in /bundle/ruby/2.7.0/gems/racc-1.5.2 for
inspection.
Results logged to
/bundle/ruby/2.7.0/extensions/x86_64-linux/2.7.0/racc-1.5.2/gem_make.out

An error occurred while installing racc (1.5.2), and Bundler cannot continue.
Make sure that `gem install racc -v '1.5.2' --source 'https://rubygems.org/'`
succeeds before bundling.

In Gemfile:
  spree was resolved to 4.3.0.rc1, which depends on
    spree_api was resolved to 4.3.0.rc1, which depends on
      spree_core was resolved to 4.3.0.rc1, which depends on
        active_storage_validations was resolved to 0.9.5, which depends on
          rails was resolved to 6.1.4, which depends on
            actioncable was resolved to 6.1.4, which depends on
              actionpack was resolved to 6.1.4, which depends on
                actionview was resolved to 6.1.4, which depends on
                  rails-dom-testing was resolved to 2.0.3, which depends on
                    nokogiri was resolved to 1.12.3, which depends on
                      racc

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /bundle/ruby/2.7.0/gems/nio4r-2.5.8/ext/nio4r
/usr/local/bin/ruby -I /usr/local/lib/ruby/2.7.0 -r
./siteconf20210816-6-jftxwh.rb extconf.rb
checking for unistd.h... yes
checking for linux/aio_abi.h... yes
checking for linux/io_uring.h... no
checking for sys/select.h... yes
checking for port_event_t in poll.h... no
checking for sys/epoll.h... yes
checking for sys/event.h... no
checking for port_event_t in port.h... no
checking for sys/resource.h... yes
creating Makefile

current directory: /bundle/ruby/2.7.0/gems/nio4r-2.5.8/ext/nio4r
make "DESTDIR=" clean
current directory: /bundle/ruby/2.7.0/gems/nio4r-2.5.8/ext/nio4r
make "DESTDIR="
make failedCannot allocate memory - make "DESTDIR="

Gem files will remain installed in /bundle/ruby/2.7.0/gems/nio4r-2.5.8 for
inspection.
Results logged to
/bundle/ruby/2.7.0/extensions/x86_64-linux/2.7.0/nio4r-2.5.8/gem_make.out

An error occurred while installing nio4r (2.5.8), and Bundler cannot continue.
Make sure that `gem install nio4r -v '2.5.8' --source 'https://rubygems.org/'`
succeeds before bundling.

In Gemfile:
  spree was resolved to 4.3.0.rc1, which depends on
    spree_api was resolved to 4.3.0.rc1, which depends on
      spree_core was resolved to 4.3.0.rc1, which depends on
        active_storage_validations was resolved to 0.9.5, which depends on
          rails was resolved to 6.1.4, which depends on
            actioncable was resolved to 6.1.4, which depends on
              nio4r

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

current directory:
/bundle/ruby/2.7.0/gems/websocket-driver-0.7.5/ext/websocket-driver
/usr/local/bin/ruby -I /usr/local/lib/ruby/2.7.0 -r
./siteconf20210816-6-d7b3ce.rb extconf.rb
extconf failedCannot allocate memory - /usr/local/bin/ruby

Gem files will remain installed in
/bundle/ruby/2.7.0/gems/websocket-driver-0.7.5 for inspection.
Results logged to
/bundle/ruby/2.7.0/extensions/x86_64-linux/2.7.0/websocket-driver-0.7.5/gem_make.out

An error occurred while installing websocket-driver (0.7.5), and Bundler cannot
continue.
Make sure that `gem install websocket-driver -v '0.7.5' --source
'https://rubygems.org/'` succeeds before bundling.

In Gemfile:
  spree was resolved to 4.3.0.rc1, which depends on
    spree_api was resolved to 4.3.0.rc1, which depends on
      spree_core was resolved to 4.3.0.rc1, which depends on
        active_storage_validations was resolved to 0.9.5, which depends on
          rails was resolved to 6.1.4, which depends on
            actioncable was resolved to 6.1.4, which depends on
              websocket-driver

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /bundle/ruby/2.7.0/gems/bcrypt-3.1.16/ext/mri
/usr/local/bin/ruby -I /usr/local/lib/ruby/2.7.0 -r
./siteconf20210816-6-1woqwvk.rb extconf.rb
extconf failedCannot allocate memory - /usr/local/bin/ruby

Gem files will remain installed in /bundle/ruby/2.7.0/gems/bcrypt-3.1.16 for
inspection.
Results logged to
/bundle/ruby/2.7.0/extensions/x86_64-linux/2.7.0/bcrypt-3.1.16/gem_make.out

An error occurred while installing bcrypt (3.1.16), and Bundler cannot continue.
Make sure that `gem install bcrypt -v '3.1.16' --source 'https://rubygems.org/'`
succeeds before bundling.

In Gemfile:
  spree_auth_devise was resolved to 4.3.4, which depends on
    devise-encryptable was resolved to 0.2.0, which depends on
      devise was resolved to 4.8.0, which depends on
        bcrypt

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /bundle/ruby/2.7.0/gems/bindex-0.8.1/ext/skiptrace
/usr/local/bin/ruby -I /usr/local/lib/ruby/2.7.0 -r
./siteconf20210816-6-6yberp.rb extconf.rb
extconf failedCannot allocate memory - /usr/local/bin/ruby

Gem files will remain installed in /bundle/ruby/2.7.0/gems/bindex-0.8.1 for
inspection.
Results logged to
/bundle/ruby/2.7.0/extensions/x86_64-linux/2.7.0/bindex-0.8.1/gem_make.out

An error occurred while installing bindex (0.8.1), and Bundler cannot continue.
Make sure that `gem install bindex -v '0.8.1' --source 'https://rubygems.org/'`
succeeds before bundling.

In Gemfile:
  web-console was resolved to 4.1.0, which depends on
    bindex

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /bundle/ruby/2.7.0/gems/msgpack-1.4.2/ext/msgpack
/usr/local/bin/ruby -I /usr/local/lib/ruby/2.7.0 -r
./siteconf20210816-6-w02fmm.rb extconf.rb
extconf failedCannot allocate memory - /usr/local/bin/ruby

Gem files will remain installed in /bundle/ruby/2.7.0/gems/msgpack-1.4.2 for
inspection.
Results logged to
/bundle/ruby/2.7.0/extensions/x86_64-linux/2.7.0/msgpack-1.4.2/gem_make.out

An error occurred while installing msgpack (1.4.2), and Bundler cannot continue.
Make sure that `gem install msgpack -v '1.4.2' --source 'https://rubygems.org/'`
succeeds before bundling.

In Gemfile:
  bootsnap was resolved to 1.7.4, which depends on
    msgpack

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /bundle/ruby/2.7.0/gems/ffi-1.15.3/ext/ffi_c
/usr/local/bin/ruby -I /usr/local/lib/ruby/2.7.0 -r
./siteconf20210816-6-brvuow.rb extconf.rb
extconf failedCannot allocate memory - /usr/local/bin/ruby

Gem files will remain installed in /bundle/ruby/2.7.0/gems/ffi-1.15.3 for
inspection.
Results logged to
/bundle/ruby/2.7.0/extensions/x86_64-linux/2.7.0/ffi-1.15.3/gem_make.out

An error occurred while installing ffi (1.15.3), and Bundler cannot continue.
Make sure that `gem install ffi -v '1.15.3' --source 'https://rubygems.org/'`
succeeds before bundling.

In Gemfile:
  spree_backend was resolved to 4.3.0.rc1, which depends on
    bootstrap was resolved to 4.6.0, which depends on
      sassc-rails was resolved to 2.1.2, which depends on
        sassc was resolved to 2.4.0, which depends on
          ffi

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /bundle/ruby/2.7.0/gems/json-2.5.1/ext/json/ext/generator
/usr/local/bin/ruby -I /usr/local/lib/ruby/2.7.0 -r
./siteconf20210816-6-12g4xrs.rb extconf.rb
extconf failedCannot allocate memory - /usr/local/bin/ruby

Gem files will remain installed in /bundle/ruby/2.7.0/gems/json-2.5.1 for
inspection.
Results logged to
/bundle/ruby/2.7.0/extensions/x86_64-linux/2.7.0/json-2.5.1/gem_make.out

An error occurred while installing json (2.5.1), and Bundler cannot continue.
Make sure that `gem install json -v '2.5.1' --source 'https://rubygems.org/'`
succeeds before bundling.

In Gemfile:
  spree_dev_tools was resolved to 0.1.8, which depends on
    simplecov was resolved to 0.13.0, which depends on
      json

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /bundle/ruby/2.7.0/gems/mysql2-0.5.3/ext/mysql2
/usr/local/bin/ruby -I /usr/local/lib/ruby/2.7.0 -r
./siteconf20210816-6-10vslpf.rb extconf.rb
extconf failedCannot allocate memory - /usr/local/bin/ruby

Gem files will remain installed in /bundle/ruby/2.7.0/gems/mysql2-0.5.3 for
inspection.
Results logged to
/bundle/ruby/2.7.0/extensions/x86_64-linux/2.7.0/mysql2-0.5.3/gem_make.out

An error occurred while installing mysql2 (0.5.3), and Bundler cannot continue.
Make sure that `gem install mysql2 -v '0.5.3' --source 'https://rubygems.org/'`
succeeds before bundling.

In Gemfile:
  spree_dev_tools was resolved to 0.1.8, which depends on
    mysql2

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /bundle/ruby/2.7.0/gems/oj-3.12.2/ext/oj
/usr/local/bin/ruby -I /usr/local/lib/ruby/2.7.0 -r
./siteconf20210816-6-qv002y.rb extconf.rb
extconf failedCannot allocate memory - /usr/local/bin/ruby

Gem files will remain installed in /bundle/ruby/2.7.0/gems/oj-3.12.2 for
inspection.
Results logged to
/bundle/ruby/2.7.0/extensions/x86_64-linux/2.7.0/oj-3.12.2/gem_make.out

An error occurred while installing oj (3.12.2), and Bundler cannot continue.
Make sure that `gem install oj -v '3.12.2' --source 'https://rubygems.org/'`
succeeds before bundling.

In Gemfile:
  oj

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /bundle/ruby/2.7.0/gems/pg-1.2.3/ext
/usr/local/bin/ruby -I /usr/local/lib/ruby/2.7.0 -r
./siteconf20210816-6-1d30pzh.rb extconf.rb
extconf failedCannot allocate memory - /usr/local/bin/ruby

Gem files will remain installed in /bundle/ruby/2.7.0/gems/pg-1.2.3 for
inspection.
Results logged to
/bundle/ruby/2.7.0/extensions/x86_64-linux/2.7.0/pg-1.2.3/gem_make.out

An error occurred while installing pg (1.2.3), and Bundler cannot continue.
Make sure that `gem install pg -v '1.2.3' --source 'https://rubygems.org/'`
succeeds before bundling.

In Gemfile:
  spree_dev_tools was resolved to 0.1.8, which depends on
    pg

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /bundle/ruby/2.7.0/gems/sqlite3-1.4.2/ext/sqlite3
/usr/local/bin/ruby -I /usr/local/lib/ruby/2.7.0 -r
./siteconf20210816-6-1cy9f5y.rb extconf.rb
extconf failedCannot allocate memory - /usr/local/bin/ruby

Gem files will remain installed in /bundle/ruby/2.7.0/gems/sqlite3-1.4.2 for
inspection.
Results logged to
/bundle/ruby/2.7.0/extensions/x86_64-linux/2.7.0/sqlite3-1.4.2/gem_make.out

An error occurred while installing sqlite3 (1.4.2), and Bundler cannot continue.
Make sure that `gem install sqlite3 -v '1.4.2' --source 'https://rubygems.org/'`
succeeds before bundling.

In Gemfile:
  spree_dev_tools was resolved to 0.1.8, which depends on
    sqlite3

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /bundle/ruby/2.7.0/gems/stackprof-0.2.17/ext/stackprof
/usr/local/bin/ruby -I /usr/local/lib/ruby/2.7.0 -r
./siteconf20210816-6-14twkf4.rb extconf.rb
extconf failedCannot allocate memory - /usr/local/bin/ruby

Gem files will remain installed in /bundle/ruby/2.7.0/gems/stackprof-0.2.17 for
inspection.
Results logged to
/bundle/ruby/2.7.0/extensions/x86_64-linux/2.7.0/stackprof-0.2.17/gem_make.out

An error occurred while installing stackprof (0.2.17), and Bundler cannot
continue.
Make sure that `gem install stackprof -v '0.2.17' --source
'https://rubygems.org/'` succeeds before bundling.

In Gemfile:
  stackprof
The command '/bin/sh -c bundle install' returned a non-zero code: 5
ERROR: Service 'web' failed to build : Build failed`

**Comment by damianlegawiec** [comment]
Did you use docker and `bin/setup`?

**Comment by pangoo-reuse** [comment]
> Did you use docker and `bin/setup`?

yes,installed  docker an run bin/setup

**Comment by linktoming** [comment]
my installation on macOS Big Sur also failed, no matter following the guide with docker or adding it to existing rails project.

**Comment by JuanVqz** [comment]
> > Did you use docker and `bin/setup`?
> 
> yes,installed docker an run bin/setup

@pangoo-reuse did you solve it? I just run `bin/setup` and all works fine within docker.
At the beginning of your first comment, you said that you have ruby `2.7.3` does that mean you are installing the repo manually? if so you should have ruby `3.0.2`

**Comment by JuanVqz** [comment]
> my installation on macOS Big Sur also failed, no matter following the guide with docker or adding it to existing rails project.
> 
> After running `bin/setup` then visiting http://localhost:3000 will forever keep loading.

docker configuration runs on `localhost:4000` would you test it, please?

**Comment by zimmerx** [comment]
Same problem can't run :(  any tips? 

Sprockets::FileNotFound in Spree::Admin::UserSessions#new

`<p style="font-family: helvetica, verdana, arial, sans-serif; font-size: 13px; line-height: 18px; color: rgb(236, 236, 236); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(34, 34, 34); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Showing<span> </span><i>/bundle/ruby/3.0.0/gems/spree_backend-4.4.0.rc1/app/views/spree/admin/shared/_head.html.erb</i><span> </span>where line<span> </span><b>#16</b><span> </span>raised:</p><pre style="font-size: 11px; white-space: pre-wrap; color: rgb(236, 236, 236); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(34, 34, 34); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><code>couldn't find file 'spree-dashboard.js'
Checked in these paths: 
  /app/app/assets/builds
  /app/app/assets/config
  /app/app/assets/images
  /app/app/assets/stylesheets
  /app/vendor/assets/javascripts
  /app/vendor/assets/stylesheets
  /bundle/ruby/3.0.0/gems/spree_backend-4.4.0.rc1/app/assets/config
  /bundle/ruby/3.0.0/gems/spree_backend-4.4.0.rc1/app/assets/images
  /bundle/ruby/3.0.0/gems/spree_backend-4.4.0.rc1/app/assets/javascripts
  /bundle/ruby/3.0.0/gems/spree_backend-4.4.0.rc1/app/assets/stylesheets
  /bundle/ruby/3.0.0/gems/spree_backend-4.4.0.rc1/vendor/assets/javascripts
  /bundle/ruby/3.0.0/gems/spree_backend-4.4.0.rc1/vendor/assets/stylesheets
  /bundle/ruby/3.0.0/gems/tinymce-rails-5.10.2/app/assets/javascripts
  /bundle/ruby/3.0.0/gems/tinymce-rails-5.10.2/app/assets/source
  /bundle/ruby/3.0.0/gems/tinymce-rails-5.10.2/vendor/assets/config
  /bundle/ruby/3.0.0/gems/tinymce-rails-5.10.2/vendor/assets/javascripts
  /bundle/ruby/3.0.0/gems/stimulus-rails-0.7.3/app/assets/javascripts
  /bundle/ruby/3.0.0/gems/turbo-rails-0.9.0/app/assets/javascripts
  /bundle/ruby/3.0.0/gems/glyphicons-1.0.2/vendor/assets/fonts
  /bundle/ruby/3.0.0/gems/glyphicons-1.0.2/vendor/assets/stylesheets
  /bundle/ruby/3.0.0/gems/flatpickr-4.6.6.0/vendor/assets/javascripts
  /bundle/ruby/3.0.0/gems/flatpickr-4.6.6.0/vendor/assets/stylesheets
  /bundle/ruby/3.0.0/gems/select2-rails-4.0.13/vendor/assets/javascripts
  /bundle/ruby/3.0.0/gems/select2-rails-4.0.13/vendor/assets/stylesheets
  /bundle/ruby/3.0.0/gems/jquery-ui-rails-6.0.1/app/assets/images
  /bundle/ruby/3.0.0/gems/jquery-ui-rails-6.0.1/app/assets/javascripts
  /bundle/ruby/3.0.0/gems/jquery-ui-rails-6.0.1/app/assets/stylesheets
  /bundle/ruby/3.0.0/gems/jquery-rails-4.4.0/vendor/assets/javascripts
  /bundle/ruby/3.0.0/gems/spree_emails-4.4.0.rc1/app/assets/config
  /bundle/ruby/3.0.0/gems/spree_emails-4.4.0.rc1/app/assets/images
  /bundle/ruby/3.0.0/gems/doorkeeper-5.5.4/app/assets/stylesheets
  /bundle/ruby/3.0.0/gems/doorkeeper-5.5.4/vendor/assets/stylesheets
  /bundle/ruby/3.0.0/gems/actioncable-6.1.4.1/app/assets/javascripts
  /bundle/ruby/3.0.0/gems/activestorage-6.1.4.1/app/assets/javascripts
  /bundle/ruby/3.0.0/gems/actionview-6.1.4.1/lib/assets/compiled
  /bundle/ruby/3.0.0/gems/popper_js-1.16.0/assets/javascripts
  /bundle/ruby/3.0.0/gems/bootstrap-4.6.1/assets/stylesheets
  /bundle/ruby/3.0.0/gems/bootstrap-4.6.1/assets/javascripts</code></pre><div class="source " id="frame-source-0-0" style="border: 1px solid rgb(85, 85, 85); background: rgb(51, 51, 51); max-width: 978px; color: rgb(236, 236, 236); font-family: helvetica, verdana, arial, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="info" style="margin: 0px; padding: 0.5em;">Extracted source (around line<span> </span><strong style="margin: 0px; padding: 0px;">#3</strong>):</div><div class="data" style="margin: 0px; padding: 0px; font-size: 10.4px; overflow: auto; background: rgb(68, 68, 68);">

1 2 3 4 5 6 | //= link_tree ../images  //= link spree-dashboard.js //= link spree/backend/all.js //= link spree/backend/all.css
-- | --


</div></div><br class="Apple-interchange-newline">`

**Comment by damianlegawiec** [comment]
> Same problem can't run :( any tips?
> 
> Sprockets::FileNotFound in Spree::Admin::UserSessions#new
> 
> `
> 
> Showing /bundle/ruby/3.0.0/gems/spree_backend-4.4.0.rc1/app/views/spree/admin/shared/_head.html.erb where line #16 raised:
> 
> ```
> couldn't find file 'spree-dashboard.js'
> Checked in these paths:
> /app/app/assets/builds
> /app/app/assets/config
> /app/app/assets/images
> /app/app/assets/stylesheets
> /app/vendor/assets/javascripts
> /app/vendor/assets/stylesheets
> /bundle/ruby/3.0.0/gems/spree_backend-4.4.0.rc1/app/assets/config
> /bundle/ruby/3.0.0/gems/spree_backend-4.4.0.rc1/app/assets/images
> /bundle/ruby/3.0.0/gems/spree_backend-4.4.0.rc1/app/assets/javascripts
> /bundle/ruby/3.0.0/gems/spree_backend-4.4.0.rc1/app/assets/stylesheets
> /bundle/ruby/3.0.0/gems/spree_backend-4.4.0.rc1/vendor/assets/javascripts
> /bundle/ruby/3.0.0/gems/spree_backend-4.4.0.rc1/vendor/assets/stylesheets
> /bundle/ruby/3.0.0/gems/tinymce-rails-5.10.2/app/assets/javascripts
> /bundle/ruby/3.0.0/gems/tinymce-rails-5.10.2/app/assets/source
> /bundle/ruby/3.0.0/gems/tinymce-rails-5.10.2/vendor/assets/config
> /bundle/ruby/3.0.0/gems/tinymce-rails-5.10.2/vendor/assets/javascripts
> /bundle/ruby/3.0.0/gems/stimulus-rails-0.7.3/app/assets/javascripts
> /bundle/ruby/3.0.0/gems/turbo-rails-0.9.0/app/assets/javascripts
> /bundle/ruby/3.0.0/gems/glyphicons-1.0.2/vendor/assets/fonts
> /bundle/ruby/3.0.0/gems/glyphicons-1.0.2/vendor/assets/stylesheets
> /bundle/ruby/3.0.0/gems/flatpickr-4.6.6.0/vendor/assets/javascripts
> /bundle/ruby/3.0.0/gems/flatpickr-4.6.6.0/vendor/assets/stylesheets
> /bundle/ruby/3.0.0/gems/select2-rails-4.0.13/vendor/assets/javascripts
> /bundle/ruby/3.0.0/gems/select2-rails-4.0.13/vendor/assets/stylesheets
> /bundle/ruby/3.0.0/gems/jquery-ui-rails-6.0.1/app/assets/images
> /bundle/ruby/3.0.0/gems/jquery-ui-rails-6.0.1/app/assets/javascripts
> /bundle/ruby/3.0.0/gems/jquery-ui-rails-6.0.1/app/assets/stylesheets
> /bundle/ruby/3.0.0/gems/jquery-rails-4.4.0/vendor/assets/javascripts
> /bundle/ruby/3.0.0/gems/spree_emails-4.4.0.rc1/app/assets/config
> /bundle/ruby/3.0.0/gems/spree_emails-4.4.0.rc1/app/assets/images
> /bundle/ruby/3.0.0/gems/doorkeeper-5.5.4/app/assets/stylesheets
> /bundle/ruby/3.0.0/gems/doorkeeper-5.5.4/vendor/assets/stylesheets
> /bundle/ruby/3.0.0/gems/actioncable-6.1.4.1/app/assets/javascripts
> /bundle/ruby/3.0.0/gems/activestorage-6.1.4.1/app/assets/javascripts
> /bundle/ruby/3.0.0/gems/actionview-6.1.4.1/lib/assets/compiled
> /bundle/ruby/3.0.0/gems/popper_js-1.16.0/assets/javascripts
> /bundle/ruby/3.0.0/gems/bootstrap-4.6.1/assets/stylesheets
> /bundle/ruby/3.0.0/gems/bootstrap-4.6.1/assets/javascripts
> ```
> 
> Extracted source (around line **#3**):
> 1 2 3 4 5 6	//= link_tree ../images //= link spree-dashboard.js //= link spree/backend/all.js //= link spree/backend/all.css
> 
> `

Please pull the latest changes that fix this issue

**Comment by zimmerx** [comment]
I've done that, but still facing this issue.  is it possible to fix it manually?  or where should I dig?

**Comment by ploitivel** [comment]
I get the following error at http://0.0.0.0:4000/admin/login

We're sorry, but something went wrong.
If you are the application owner check the logs for more information.

When reviewing the logs of the container already compiled in production, I get the following error
$docker logs container

I, [2023-01-21T19:18:44.376702 #51] INFO -- : [ae9df578-5457-4485-a3c2-88ad34b31cb8] Completed 500 Internal Server Error in 439ms (ActiveRecord: 59.6ms | Allocations: 26850)
F, [2023-01-21T19:18:44.380758 #51] FATAL -- : [ae9df578-5457-4485-a3c2-88ad34b31cb8]
[ae9df578-5457-4485-a3c2-88ad34b31cb8] ActionView::Template::Error (The asset "spree/backend/all.css" is not present in the asset pipeline.
):
[ae9df578-5457-4485-a3c2-88ad34b31cb8] 13: <% end %>
[ae9df578-5457-4485-a3c2-88ad34b31cb8] 14: </title>
[ae9df578-5457-4485-a3c2-88ad34b31cb8] 15:
[ae9df578-5457-4485-a3c2-88ad34b31cb8] 16: <%= stylesheet_link_tag 'spree/backend/all', media: :all %>
[ae9df578-5457-4485-a3c2-88ad34b31cb8] 17:
[ae9df578-5457-4485-a3c2-88ad34b31cb8] 18: <script>
[ae9df578-5457-4485-a3c2-88ad34b31cb8] 19: <%== "var AUTH_TOKEN = #{form_authenticity_token.inspect};" %>
[ae9df578-5457-4485-a3c2-88ad34b31cb8]
[ae9df578-5457-4485-a3c2-88ad34b31cb8] lib/cloud_flare_middleware.rb:18:in `call'
I, [2023-01-21T19:18:44.393543 #51] INFO -- : source=rack-timeout id=ae9df578-5457-4485-a3c2-88ad34b31cb8 timeout=15000ms service=466ms state=completed
