### ISSUE TITLE
"*** stack smashing detected ***: terminated" on M1 Apple Silicon

### ISSUE THREAD

**Issue by 4ndv** [spree/spree_starter#984]
Follow up to #980 and #968

When installing using docker on M1 Mac, when trying to visit http://localhost:4000/admin there is this error in the logs:

```
spree_starter-web-1       | Processing by Spree::Admin::UserSessionsController#new as HTML
spree_starter-web-1       |   Rendering layout /bundle/ruby/3.0.0/gems/spree_auth_devise-4.4.0/lib/views/backend/spree/layouts/login.html.erb
spree_starter-web-1       |   Rendering /bundle/ruby/3.0.0/gems/spree_auth_devise-4.4.0/lib/views/backend/spree/admin/user_sessions/new.html.erb within spree/layouts/login
spree_starter-web-1       |   Rendered /bundle/ruby/3.0.0/gems/spree_auth_devise-4.4.0/lib/views/backend/spree/admin/user_sessions/new.html.erb within spree/layouts/login (Duration: 1421.1ms | Allocations: 1869480)
spree_starter-web-1       | *** stack smashing detected ***: terminated
spree_starter-web-1       | [1] - Worker 1 (PID: 275) booted in 0.02s, phase: 0
spree_starter-web-1       | Started GET "/admin/login" for 172.18.0.1 at 2021-11-04 10:26:33 +0000
```

Steps to reproduce:

```
$ git clone git@github.com:spree/spree_starter.git

$ bin/setup

visit http://localhost:4000/admin
```

Looks like the problem is related to `mini_racer` gem

**Comment by 4ndv** [comment]
Here's how to fix it until there is new version of `mini_racer` out of prerelease:

In `Gemfile` change `gem 'mini_racer'` to `gem 'mini_racer', github: 'rubyjs/mini_racer'`

Then `docker compose run --rm web bash -c 'bundle install'`

Then `docker compose build web worker`

Then `bin/start` and everything should work fine.

**Comment by 4ndv** [comment]
Related to rubyjs/mini_racer#190

**Comment by tisba** [comment]
You could give `mini_racer` `0.5.0.pre` a try. It seems to have fixed the issue https://github.com/rubyjs/mini_racer/issues/190

```ruby
gem "mini_racer", "0.5.0.pre"
gem "libv8-node", "16.10.0.0"
```

**Comment by damianlegawiec** [comment]
We've dropped `mini_racer` in favour of the native node as we're using https://github.com/rails/jsbundling-rails now
