### ISSUE TITLE
Product Form Fields Show Duplicates 

### ISSUE THREAD

**Issue by rafaelmonroy** [spree/spree_starter#989]
When hitting the browser(google chrome, safari (desktop and mobile)) back bottom after leaving any `/admin/products/:product/edit` route, the taxons, option types, store and any fields that have data duplicate themselves
<img width="687" alt="Screen Shot 2021-12-28 at 4 24 07 PM" src="https://user-images.githubusercontent.com/53493117/147618050-21fd13e1-91ef-4b79-a6a3-54bf9a18d0c8.png">
 
This happens on a vanilla deploy on Heroku

To reproduce 

1. visit any product edit page
2. click on any link that navigates you away from that page
3. hit the back button on your browser
4. you will see the duplicate fields shown in the screenshot above 

TEST HERE https://test-spree-4-4-starter.herokuapp.com/admin/login

**Comment by damianlegawiec** [comment]
Thanks @rafaelmonroy , this is now fixed with Spree 4.4 RC2

**Comment by sebbean** [comment]
@damianlegawiec 🙏
